"""
    Module name :- 0001_initial
"""

# Generated by Django 4.2.11 on 2024-03-05 08:22

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Migration class.
    """

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("author", models.CharField(max_length=50)),
                ("publication_date", models.DateField(auto_now_add=True)),
                ("isbn", models.CharField(max_length=13)),
            ],
        ),
    ]
