# Generated by Django 4.2.11 on 2024-03-05 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_alter_book_publication_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="isbn",
            field=models.CharField(
                help_text="Enter only 13 characters.", max_length=13
            ),
        ),
    ]
