"""
    Module name :- 0004_...
"""

# Generated by Django 4.2.11 on 2024-03-06 04:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Migration class.
    """

    dependencies = [
        ("books", "0003_alter_book_isbn"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="isbn",
            field=models.CharField(
                help_text="Enter only 13 characters.",
                max_length=13,
                validators=[django.core.validators.MinLengthValidator(13)],
            ),
        ),
    ]
