"""
    Module name :- 0001_initial
"""

# Generated by Django 4.2.11 on 2024-03-05 09:30

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Migration class.
    """

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("make", models.CharField(max_length=50)),
                ("model", models.CharField(max_length=50)),
                ("year", models.IntegerField()),
                (
                    "transmission",
                    models.CharField(
                        choices=[("Manual", "Manual"), ("Automatic", "Automatic")],
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
