"""
    Module name :- 0002_..
"""

# Generated by Django 4.2.11 on 2024-03-05 09:33

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Migration class.
    """

    dependencies = [
        ("car", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="transmission",
            field=models.CharField(
                choices=[("Manual", "Manual"), ("Automatic", "Automatic")],
                default="Manual",
                max_length=20,
            ),
        ),
    ]
